import tkinter as tk


window = tk.Tk()
window.title("Калькулятор")
window.geometry("400x400")
window.resizable(False,False)
button_add = tk.Button(window, text='+', width=5, height=5)
button_add.place(x=90, y=300)
button_sub = tk.Button(window, text='-', width=5, height=5)
button_sub.place(x=150, y=300)
button_mul = tk.Button(window, text='*', width=5, height=5)
button_mul.place(x=210, y=300)
button_div = tk.Button(window, text='/', width=5, height=5)
button_div.place(x=270, y=300)
number1_entry = tk.Entry(window, width=25)
number1_entry.place(x=30, y=50)
number2_entry = tk.Entry(window, width=25)
number2_entry.place(x=216, y=50)
answer_entry = tk.Entry(window, width=55)
answer_entry.place(x=30, y=150)
number1 = tk.Label(window, text='Введите первое число:')
number1.place(x=30, y=25)
number2 = tk.Label(window, text='Введите второе число:')
number2.place(x=216, y=25)
answer_ = tk.Label(window, text='Ответ:')
answer_.place(x=30, y=125)
window.mainloop()

